export default [
    {
        id:7,
        name:'Cryptoverse',
        imageUrl:'./Projects/cryptoverse.png',
        liveLink:'https://cryptoverse5867.netlify.app/',
        githubLink:'https://github.com/sukanyagurav/Cryptoverse',
        category:'featured',
        description:'Live cryptocurrency tracker with real-time price data, market cap rankings, and per-coin detail pages backed by a public REST API.',
        tech:['React', 'REST API', 'Chart.js', 'CSS'],
    },
    {
        id:4,
        name:'Merch Maze — Ecommerce Cart',
        imageUrl:'./Projects/Merch-Maze-ecommerce-site.png',
        liveLink:'https://merchmaze5867.netlify.app/',
        githubLink:'https://github.com/sukanyagurav/Ecommerce-site',
        category:'featured',
        description:'Full storefront flow with product listing, cart state management, quantity controls, and order summary logic built from scratch.',
        tech:['React', 'Context API', 'Tailwind CSS'],
    },
    {
        id:11,
        name:'Find Your Stay',
        imageUrl:'./Projects/art-gallery-website.jpg',
        liveLink:'https://find-your-stays-5867.netlify.app/',
        githubLink:'https://github.com/sukanyagurav/Property-Listing-App',
        category:'featured',
        description:'Property listing and search app with filterable results, detail views, and a responsive grid inspired by Airbnb-style booking UIs.',
        tech:['React', 'React Router', 'Tailwind CSS'],
    },
    {
        id:2,
        name:'BingeVerse',
        imageUrl:'./Projects/entertainment-web-app.jpg',
        liveLink:'https://entertainmentwebapp67.netlify.app/',
        githubLink:'https://github.com/sukanyagurav/Entertainment-web-app',
        category:'featured',
        description:'Media browsing app with category filtering (movies, TV, trending), search, and a bookmarking system persisted across sessions.',
        tech:['React', 'JavaScript', 'CSS Grid'],
    },
    {
        id:9,
        name:'Coffee Roasters — Subscription Site',
        imageUrl:'./Projects/coffeeroasters.jpg',
        liveLink:'https://cofferoasters-subscription-site-fm.netlify.app/',
        githubLink:'https://github.com/sukanyagurav/coffeeroasters-subscription-site',
        category:'featured',
        description:'Multi-section marketing site with a subscription plan selector, scroll-based reveals, and pixel-precise responsive layouts.',
        tech:['JavaScript', 'CSS Grid', 'Responsive Design'],
    },
    {
        id:16,
        name:'REST Countries Explorer',
        imageUrl:'./Projects/rest-countries.jpg',
        liveLink:'https://cozy-bubblegum-05c07a.netlify.app/#',
        githubLink:'https://github.com/sukanyagurav/REST-Countries-API-with-color-theme-switcher',
        category:'featured',
        description:'Country data explorer consuming a public REST API, with search, region filtering, and a persisted light/dark theme switcher.',
        tech:['JavaScript', 'REST API', 'CSS Variables'],
    },
    {
        id:17,
        name:'IP Address Tracker',
        imageUrl:'./Projects/IP-Address-Tracker.jpg',
        liveLink:'https://iptrakcer.netlify.app/',
        githubLink:'https://github.com/sukanyagurav/IP-address-tracker',
        category:'featured',
        description:'Geolocation lookup tool that plots any IP or domain on an interactive map using a third-party geolocation API.',
        tech:['JavaScript', 'Leaflet.js', 'REST API'],
    },
    {
        id:3,
        name:'Conference Ticket Generator',
        imageUrl:'./Projects/conference-ticket-generator.jpg',
        liveLink:'https://conference-ticket-generator5867.netlify.app/',
        githubLink:'https://github.com/sukanyagurav/Conference-ticket-generator',
        category:'featured',
        description:'Multi-step form with client-side validation, drag-and-drop avatar upload, and a dynamically generated event ticket.',
        tech:['JavaScript', 'Form Validation', 'CSS'],
    },
    {
        id:1,
        name:'Character Counter',
        imageUrl:'./Projects/character-counter-preview.jpg',
        liveLink:'https://charactercount5867.netlify.app/',
        githubLink:'https://github.com/sukanyagurav/Character-counter',
        category:'practice',
    },
    {
        id:5,
        name:'Galleria',
        imageUrl:'./Projects/galleria.png',
        liveLink:'https://galleria5867.netlify.app/',
        githubLink:'https://github.com/sukanyagurav/Galleria',
        category:'practice',
    },
    {
        id:6,
        name:'Buy Desserts',
        imageUrl:'./Projects/buy-your-desserts.jpg',
        liveLink:'https://buydesserts5867.netlify.app/',
        githubLink:'https://github.com/sukanyagurav/Buy-Desserts',
        category:'practice',
    },
    {
        id:8,
        name:'Coffee Collections',
        imageUrl:'./Projects/coffeelisting.png',
        liveLink:'https://coffeelisting5867.netlify.app/',
        githubLink:'https://github.com/sukanyagurav/Coffee-listing-page',
        category:'practice',
    },
    {
        id:10,
        name:'Art Gallery Site',
        imageUrl:'./Projects/art-gallery-website.jpg',
        liveLink:'https://art-gallery-website-mrtjhn6f3-sukanya-guravs-projects.vercel.app/',
        githubLink:'https://github.com/sukanyagurav/Art-gallery-website',
        category:'practice',
    },
    {
        id:12,
        name:'Launch Countdown Timer',
        imageUrl:'./Projects/Launch-countdown-timer.jpg',
        liveLink:'https://sukanyagurav.github.io/Frontend-Mentor---Launch-countdown-timer/',
        githubLink:'https://github.com/sukanyagurav/Frontend-Mentor---Launch-countdown-timer',
        category:'practice',
    },
    {
        id:13,
        name:'Dictionary Web App',
        imageUrl:'./Projects/Dictionary-web-app.jpg',
        liveLink:'https://sukanyagurav.github.io/Dictionary-Web-App---Frontend-Mentor-Challenge/',
        githubLink:'https://github.com/sukanyagurav/Dictionary-Web-App---Frontend-Mentor-Challenge',
        category:'practice',
    },
    {
        id:14,
        name:'Job Listings with Filtering',
        imageUrl:'./Projects/Job-listings-with-filtering.jpg',
        liveLink:'https://sukanyagurav.github.io/Job-listings-with-filtering-challenge-on-Frontend-Mentor/',
        githubLink:'https://github.com/sukanyagurav/Job-listings-with-filtering-challenge-on-Frontend-Mentor',
        category:'practice',
    },
    {
        id:15,
        name:'Planet Fact Site',
        imageUrl:'./Projects/Planets-fact-site.jpg',
        liveLink:'https://sukanyagurav.github.io/Frontend-Mentor---Planets-fact-site-solution/',
        githubLink:'https://github.com/sukanyagurav/Frontend-Mentor---Planets-fact-site-solution',
        category:'practice',
    },
    {
        id:19,
        name:'Clock App',
        imageUrl:'./Projects/clock-app.jpg',
        liveLink:'https://sukanyagurav.github.io/Frontend-Mentor---Clock-app/',
        githubLink:'https://github.com/sukanyagurav/Frontend-Mentor---Clock-app',
        category:'practice',
    },
    {
        id:20,
        name:'Maker Landing Page',
        imageUrl:'./Projects/Maker-landing-page.jpg',
        liveLink:'https://maker5867.netlify.app/',
        githubLink:'https://github.com/sukanyagurav/Maker-pre-launch-landing-page',
        category:'practice',
    },
    {
        id:21,
        name:'MovieFix App',
        imageUrl:'./Projects/Movie-Fix-App.png',
        liveLink:'https://movielistco.netlify.app/',
        githubLink:'https://github.com/sukanyagurav/Movie_Fix_app',
        category:'practice',
    },
    {
        id:22,
        name:'Tip Calculator',
        imageUrl:'./Projects/tip-calculator-app-main.jpg',
        liveLink:'https://sukanyagurav.github.io/tip-calculator-app-main/',
        githubLink:'https://github.com/sukanyagurav/tip-calculator-app-main',
        category:'practice',
    },
    {
        id:23,
        name:'Loopstudios Landing Page',
        imageUrl:'./Projects/Loopstudios-landing-page.jpg',
        liveLink:'https://stellular-mandazi-f5268b.netlify.app/',
        githubLink:'https://github.com/sukanyagurav/Frontend-Mentor---Loopstudios-landing-page',
        category:'practice',
    },
    {
        id:24,
        name:'Password Generator App',
        imageUrl:'./Projects/Password-generator-app.jpg',
        liveLink:'https://sukanyagurav.github.io/Frontend-Mentor---Password-Generator-App-Solution/',
        githubLink:'https://github.com/sukanyagurav/Frontend-Mentor---Password-Generator-App-Solution',
        category:'practice',
    },
    {
        id:25,
        name:'Age Calculator App',
        imageUrl:'./Projects/ageCalculator.jpg',
        liveLink:'https://sukanyagurav.github.io/age-calculator-app-main/',
        githubLink:'https://github.com/sukanyagurav/age-calculator-app-main',
        category:'practice',
    },
    {
        id:26,
        name:'Recipe Page',
        imageUrl:'./Projects/Recipe-page.jpg',
        liveLink:'https://sukanyagurav.github.io/Frontend-mentor-challenge-recipe-page-main/',
        githubLink:'https://github.com/sukanyagurav/Frontend-mentor-challenge-recipe-page-main',
        category:'practice',
    },
    {
        id:27,
        name:'Advice Generator App',
        imageUrl:'./Projects/AdviceGenerator.jpg',
        liveLink:'https://sukanyagurav.github.io/advice-generator-app-main-/',
        githubLink:'https://github.com/sukanyagurav/advice-generator-app-main-',
        category:'practice',
    },
    {
        id:28,
        name:'Pomodoro Timer',
        imageUrl:'./Projects/Pomodoro-timer.jpg',
        liveLink:'https://sukanyagurav.github.io/Pomodoro-timer/',
        githubLink:'https://github.com/sukanyagurav/Pomodoro-timer',
        category:'practice',
    },
    {
        id:29,
        name:'Multi Step Form',
        imageUrl:'./Projects/Multi-step-form.jpg',
        liveLink:'https://sukanyagurav.github.io/Frontend-Mentor---Multi-step-form/',
        githubLink:'https://github.com/sukanyagurav/Frontend-Mentor---Multi-step-form',
        category:'practice',
    },
    {
        id:30,
        name:'Room Homepage',
        imageUrl:'./Projects/Room-homepage.jpg',
        liveLink:'https://sukanyagurav.github.io/Frontend-mentor-challenge-Room-homepage-coding-challenge/',
        githubLink:'https://github.com/sukanyagurav/Frontend-mentor-challenge-Room-homepage-coding-challenge/tree/main',
        category:'practice',
    },
    {
        id:31,
        name:'Chat App CSS Illustration',
        imageUrl:'./Projects/Chat-app-CSS-illustration.jpg',
        liveLink:'https://sukanyagurav.github.io/Chat-app-CSS-illustration/',
        githubLink:'https://github.com/sukanyagurav/Chat-app-CSS-illustration/tree/master',
        category:'practice',
    },
    {
        id:32,
        name:'Four Card Feature Section',
        imageUrl:'./Projects/Four-card-feature-section.jpg',
        liveLink:'https://sukanyagurav.github.io/four-card-feature-section-master/',
        githubLink:'https://github.com/sukanyagurav/four-card-feature-section-master/tree/master',
        category:'practice',
    },
    {
        id:33,
        name:'Readbook Landing Page',
        imageUrl:'./Projects/readbooks.JPG',
        liveLink:'https://sukanyagurav.github.io/readbooks/',
        githubLink:'https://github.com/sukanyagurav/readbooks/tree/master',
        category:'practice',
    },
    {
        id:34,
        name:'Clipboard Landing Page',
        imageUrl:'./Projects/Clipboard-Landing-page.jpg',
        liveLink:'https://sukanyagurav.github.io/Clipboard-landing-page/',
        githubLink:'https://github.com/sukanyagurav/Clipboard-landing-page',
        category:'practice',
    },
    {
        id:35,
        name:'FAQ Accordion',
        imageUrl:'./Projects/FAQ-accordion.jpg',
        liveLink:'https://sukanyagurav.github.io/Frontend-Mentor---FAQ-accordion/',
        githubLink:'https://github.com/sukanyagurav/Frontend-Mentor---FAQ-accordion',
        category:'practice',
    },
    {
        id:36,
        name:'Intro Component with Sign-up Form',
        imageUrl:'./Projects/Intro-component-with-sign-up-form.jpg',
        liveLink:'https://sukanyagurav.github.io/intro-component-with-signup-form-master/',
        githubLink:'https://github.com/sukanyagurav/intro-component-with-signup-form-master/tree/master',
        category:'practice',
    },
    {
        id:37,
        name:'Notifications Page',
        imageUrl:'./Projects/notifications-page-main.jpg',
        liveLink:'https://sukanyagurav.github.io/Notifications-page/',
        githubLink:'https://github.com/sukanyagurav/Notifications-page',
        category:'practice',
    },
    {
        id:38,
        name:'Interactive Card Details Form',
        imageUrl:'./Projects/interactive-card-details-form-main.jpg',
        liveLink:'https://sukanyagurav.github.io/Interactive-card-details-form-/',
        githubLink:'https://github.com/sukanyagurav/Interactive-card-details-form-',
        category:'practice',
    },
    {
        id:39,
        name:'Newsletter Sign-up with Success Message',
        imageUrl:'./Projects/newsletter-sign-up-with-success-message-main.jpg',
        liveLink:'https://sukanyagurav.github.io/newsletter-sign-up-with-success-message-main/',
        githubLink:'https://github.com/sukanyagurav/newsletter-sign-up-with-success-message-main',
        category:'practice',
    },
    {
        id:40,
        name:'Coding Bootcamp Testimonials Slider',
        imageUrl:'./Projects/carousel.jpg',
        liveLink:'https://sukanyagurav.github.io/coding-bootcamp-testimonials-slider-master/',
        githubLink:'https://github.com/sukanyagurav/coding-bootcamp-testimonials-slider-master',
        category:'practice',
    },
    {
        id:41,
        name:'Sunnyside Agency Landing Page',
        imageUrl:'./Projects/sunnyside-agency-landing-page-main.jpg',
        liveLink:'https://sukanyagurav.github.io/Sunnyside-agency-landing-page/',
        githubLink:'https://github.com/sukanyagurav/Sunnyside-agency-landing-page',
        category:'practice',
    },
    {
        id:42,
        name:'Intro Section with Dropdown Navigation',
        imageUrl:'./Projects/intro-section-with-dropdown-navigation-main.jpg',
        liveLink:'https://sukanyagurav.github.io/Intro-section-with-dropdown-navigation/',
        githubLink:'https://github.com/sukanyagurav/Intro-section-with-dropdown-navigation',
        category:'practice',
    },
    {
        id:43,
        name:'Interactive Rating Component',
        imageUrl:'./Projects/interactive-rating-component-main.jpg',
        liveLink:'https://sukanyagurav.github.io/interactive-rating-component-main/',
        githubLink:'https://github.com/sukanyagurav/interactive-rating-component-main/tree/master',
        category:'practice',
    },
    {
        id:101,
        name:'Pricing Component with Toggle',
        imageUrl:'./Projects/pricing-component-with-toggle-master.jpg',
        liveLink:'https://sukanyagurav.github.io/pricing-component-with-toggle-master/',
        githubLink:'https://github.com/sukanyagurav/pricing-component-with-toggle-master',
        category:'practice',
    },
    {
        id:102,
        name:'Testimonials Grid Section',
        imageUrl:'./Projects/testimonials-grid-section-main.jpg',
        liveLink:'https://sukanyagurav.github.io/testimonials-grid-section-main/',
        githubLink:'https://github.com/sukanyagurav/testimonials-grid-section-main/tree/master',
        category:'practice',
    },
    {
        id:103,
        name:'News Homepage',
        imageUrl:'./Projects/news-homepage-main.jpg',
        liveLink:'https://sukanyagurav.github.io/news-homepage-main/',
        githubLink:'https://github.com/sukanyagurav/news-homepage-main/tree/master',
        category:'practice',
    },
    {
        id:44,
        name:'Social Proof Section',
        imageUrl:'./Projects/social-proof-section-master.jpg',
        liveLink:'https://sukanyagurav.github.io/social-proof-section-master/',
        githubLink:'https://github.com/sukanyagurav/social-proof-section-master/tree/master',
        category:'practice',
    },
    {
        id:45,
        name:'Results Summary Component',
        imageUrl:'./Projects/results-summary-component-main.jpg',
        liveLink:'https://sukanyagurav.github.io/results-summary-component-main/',
        githubLink:'https://github.com/sukanyagurav/results-summary-component-main',
        category:'practice',
    },
    {
        id:46,
        name:'Fylo Data Storage Component',
        imageUrl:'./Projects/Fylo-data-storage-component-master.jpg',
        liveLink:'https://sukanyagurav.github.io/fylo-data-storage-component-master/',
        githubLink:'https://github.com/sukanyagurav/fylo-data-storage-component-master/tree/master',
        category:'practice',
    },
    {
        id:47,
        name:'Insure Landing Page',
        imageUrl:'./Projects/Insure-landing-page.jpg',
        liveLink:'https://sukanyagurav.github.io/Frontend-Mentor---Insure-landing-page/',
        githubLink:'https://github.com/sukanyagurav/Frontend-Mentor---Insure-landing-page',
        category:'practice',
    },
    {
        id:104,
        name:'Expenses Chart Component',
        imageUrl:'./Projects/expenses-chart-component-main.jpg',
        liveLink:'https://sukanyagurav.github.io/expenses-chart-component-main/',
        githubLink:'https://github.com/sukanyagurav/expenses-chart-component-main',
        category:'practice',
    },
    {
        id:105,
        name:'FAQ Accordion Card',
        imageUrl:'./Projects/faq-accordion-card-main.jpg',
        liveLink:'https://sukanyagurav.github.io/faq-accordion-card-main/',
        githubLink:'https://github.com/sukanyagurav/faq-accordion-card-main/tree/master',
        category:'practice',
    },
    {
        id:106,
        name:'Fylo Dark Theme Landing Page',
        imageUrl:'./Projects/fylo-dark-theme-landing-page-master.jpg',
        liveLink:'https://sukanyagurav.github.io/fylo-dark-theme-landing-page-master/',
        githubLink:'https://github.com/sukanyagurav/fylo-dark-theme-landing-page-master',
        category:'practice',
    },
    {
        id:107,
        name:'Game Landing Page',
        imageUrl:'./Projects/game-landing-page.JPG',
        liveLink:'https://sukanyagurav.github.io/game-landing-page/',
        githubLink:'https://github.com/sukanyagurav/game-landing-page/tree/master',
        category:'practice',
    },
]
